version: "3.8"
services:
   db:
    image: postgres:latest
    ports:
      - 5434:5432
    env_file:
      - environment.env
    environment:
      - POSTGRES_USER=$(POSTGRES_USER)
      - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
      - POSTGRES_DB=$(POSTGRES_DB)
    volumes:
      - /var/lib/docker/volumes/test/_data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
