version: "3.8"
services:
   db:
    image: postgres:latest
    ports:
      - 5434:5432
    env_file:
      - environment.env
    volumes:
      - /var/lib/docker/volumes/test/_data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
